-- Query for Execution plan run times
select
W_ETL_DEFN_RUN.ETL_PROC_WID,
W_ETL_DEFN.NAME as EXEC_PLAN_NAME,
W_ETL_DEFN.LAST_DESIGN_DT,
W_ETL_DEFN_RUN.NAME, W_ETL_DEFN_RUN.ETL_DEFN_NAME,
W_ETL_DEFN_RUN.STATUS AS RUN_STATUS,
W_ETL_DEFN_RUN.STATUS_DESC as RUN_STATUS_DESC,
W_ETL_DEFN_RUN.TOTAL_STEPS as TOTAL_STEPS_RUN,
W_ETL_DEFN_RUN.SUCC_STEPS as TOTAL_SUCC_STEPS_RUN,
W_ETL_DEFN_RUN.START_TS as RUN_START_TIME,
W_ETL_DEFN_RUN.END_TS as RUN_END_IME,
round((W_ETL_DEFN_RUN.END_TS - W_ETL_DEFN_RUN.START_TS)*24*60) ETL_RUN_DURATION_MINS
FROM
ORACLEDAC.W_ETL_DEFN_RUN,
ORACLEDAC.W_ETL_DEFN
WHERE
W_ETL_DEFN.ROW_WID = W_ETL_DEFN_RUN.ETL_DEFN_WID
ORDER BY ETL_PROC_WID DESC


-- Query for Execution plan with each step run times
select
W_ETL_DEFN_RUN.ETL_PROC_WID,
W_ETL_STEP.ROW_WID,
W_ETL_RUN_STEP.STEP_NAME,
W_ETL_STEP.CMD_NAME as COMMAND_NAME,
W_ETL_STEP.FL_CMD_NAME as FULL_COMMAND_NAME,
W_ETL_RUN_STEP.PHY_SRC_NAME,
W_ETL_RUN_STEP.PHY_TRGT_NAME,
W_ETL_RUN_STEP.PHY_FOLDER_NAME,
W_ETL_RUN_STEP.APP_WID as SOURCE_SYSTEM_CONTAINER,
W_ETL_RUN_STEP.DEPTH,
W_ETL_RUN_STEP.PHASE_NAME,
W_ETL_RUN_STEP.START_TS as STEP_START_TIME,
W_ETL_RUN_STEP.END_TS as STEP_END_TIME,
W_ETL_RUN_STEP.STATUS as STEP_STATUS,
W_ETL_RUN_STEP.SUCESS_ROWS as STEP_SUCCESS_ROWS,
W_ETL_RUN_STEP.FAILED_ROWS STEP_FAILED_ROWS,
W_ETL_RUN_STEP.STATUS_DESC as STEP_STATUS_DESC,
round((W_ETL_RUN_STEP.END_TS-W_ETL_RUN_STEP.START_TS)*24*60) ETL_RUN_STEP_DURATION_MINS
from
ORACLEDAC.W_ETL_DEFN_RUN,
ORACLEDAC.W_ETL_RUN_STEP,
ORACLEDAC.W_ETL_STEP
WHERE
W_ETL_DEFN_RUN.ROW_WID = W_ETL_RUN_STEP.RUN_WID AND
W_ETL_RUN_STEP.STEP_WID = W_ETL_STEP.ROW_WID
ORDER BY W_ETL_DEFN_RUN.ETL_PROC_WID DESC, W_ETL_RUN_STEP.DEPTH ASC


-- Query for Execution plan with each step details run times
select
W_ETL_DEFN_RUN.ETL_PROC_WID,
W_ETL_RUN_STEP.DEPTH,
W_ETL_STEP.ROW_WID as RUN_STEP_WID,
W_ETL_RUN_SDTL.ROW_WID as RUN_STEP_SDTL_WID,
W_ETL_RUN_SDTL.NAME as TASK_SDTL_NAME,
W_ETL_RUN_SDTL.TYPE_CD as TASK_SDTL_TYPE,
W_ETL_RUN_SDTL.STATUS_CD as TASK_SDTL_STATUS,
W_ETL_RUN_SDTL.START_TS as TASK_SDTL_START_TIME,
W_ETL_RUN_SDTL.END_TS as TASK_SDTL_END_TIME,
W_ETL_RUN_SDTL.SUCESS_ROWS as TASK_SDTL_SUCCESS_ROWS,
W_ETL_RUN_SDTL.STATUS_DESC as TASK_SDTL_STATUS_DESC,
W_ETL_INDEX.ISBITMAP,
W_ETL_INDEX.NAME as INDEX_NAME,
W_ETL_TABLE.NAME as TABLE_NAME,
W_ETL_TABLE.TYPE_CD as TABLE_TYPE_CODE,
ROUND((W_ETL_RUN_SDTL.END_TS-W_ETL_RUN_SDTL.START_TS)*24*60) AS ETL_STEP_SDTL_DURN_MINS
from
ORACLEDAC.W_ETL_DEFN_RUN,
ORACLEDAC.W_ETL_RUN_STEP,
ORACLEDAC.W_ETL_RUN_SDTL,
ORACLEDAC.W_ETL_INDEX,
ORACLEDAC.W_ETL_TABLE,
ORACLEDAC.W_ETL_STEP
WHERE
W_ETL_DEFN_RUN.ROW_WID = W_ETL_RUN_STEP.RUN_WID AND
W_ETL_RUN_SDTL.RUN_STEP_WID = W_ETL_RUN_STEP.ROW_WID AND
W_ETL_RUN_SDTL.INDEX_WID = W_ETL_INDEX.ROW_WID(+) AND
W_ETL_RUN_SDTL.TABLE_WID = W_ETL_TABLE.ROW_WID(+) AND
W_ETL_RUN_STEP.STEP_WID = W_ETL_STEP.ROW_WID
ORDER BY W_ETL_DEFN_RUN.ETL_PROC_WID DESC, W_ETL_RUN_STEP.DEPTH ASC, W_ETL_RUN_SDTL.ROW_WID


-- Single query that gives details of execution plan all the way to the detail
select
W_ETL_DEFN_RUN.ETL_PROC_WID,
W_ETL_DEFN.NAME as EXEC_PLAN_NAME,
W_ETL_DEFN.LAST_DESIGN_DT,
W_ETL_DEFN_RUN.NAME, W_ETL_DEFN_RUN.ETL_DEFN_NAME,
W_ETL_DEFN_RUN.STATUS AS RUN_STATUS,
W_ETL_DEFN_RUN.STATUS_DESC as RUN_STATUS_DESC,
W_ETL_DEFN_RUN.TOTAL_STEPS as TOTAL_STEPS_RUN,
W_ETL_DEFN_RUN.SUCC_STEPS as TOTAL_SUCC_STEPS_RUN,
W_ETL_DEFN_RUN.START_TS as RUN_START_TIME,
W_ETL_DEFN_RUN.END_TS as RUN_END_IME,
W_ETL_RUN_STEP.STEP_NAME,
W_ETL_STEP.CMD_NAME as COMMAND_NAME,
W_ETL_STEP.FL_CMD_NAME as FULL_COMMAND_NAME,
W_ETL_RUN_STEP.PHY_SRC_NAME,
W_ETL_RUN_STEP.PHY_TRGT_NAME,
W_ETL_RUN_STEP.PHY_FOLDER_NAME,
W_ETL_RUN_STEP.APP_WID as SOURCE_SYSTEM_CONTAINER,
W_ETL_RUN_STEP.DEPTH,
W_ETL_RUN_STEP.PHASE_NAME,
W_ETL_RUN_STEP.START_TS as STEP_START_TIME,
W_ETL_RUN_STEP.END_TS as STEP_END_TIME,
W_ETL_RUN_STEP.STATUS as STEP_STATUS,
W_ETL_RUN_STEP.SUCESS_ROWS as STEP_SUCCESS_ROWS,
W_ETL_RUN_STEP.FAILED_ROWS STEP_FAILED_ROWS,
W_ETL_RUN_STEP.STATUS_DESC as STEP_STATUS_DESC,
W_ETL_RUN_SDTL.NAME as TASK_SDTL_NAME,
W_ETL_RUN_SDTL.TYPE_CD as TASK_SDTL_TYPE,
W_ETL_RUN_SDTL.STATUS_CD as TASK_SDTL_STATUS,
W_ETL_RUN_SDTL.START_TS as TASK_SDTL_START_TIME,
W_ETL_RUN_SDTL.END_TS as TASK_SDTL_END_TIME,
W_ETL_RUN_SDTL.SUCESS_ROWS as TASK_SDTL_SUCCESS_ROWS,
W_ETL_RUN_SDTL.STATUS_DESC as TASK_SDTL_STATUS_DESC,
W_ETL_INDEX.ISBITMAP,
W_ETL_INDEX.NAME as INDEX_NAME,
W_ETL_TABLE.NAME as TABLE_NAME,
W_ETL_TABLE.TYPE_CD as TABLE_TYPE_CODE
from
ORACLEDAC.W_ETL_DEFN_RUN,
ORACLEDAC.W_ETL_RUN_STEP,
ORACLEDAC.W_ETL_RUN_SDTL,
ORACLEDAC.W_ETL_INDEX,
ORACLEDAC.W_ETL_TABLE,
ORACLEDAC.W_ETL_DEFN,
ORACLEDAC.W_ETL_STEP
WHERE
W_ETL_DEFN.ROW_WID = W_ETL_DEFN_RUN.ETL_DEFN_WID AND
W_ETL_DEFN_RUN.ROW_WID = W_ETL_RUN_STEP.RUN_WID AND
W_ETL_RUN_SDTL.RUN_STEP_WID = W_ETL_RUN_STEP.ROW_WID AND
W_ETL_RUN_SDTL.INDEX_WID = W_ETL_INDEX.ROW_WID(+) AND
W_ETL_RUN_SDTL.TABLE_WID = W_ETL_TABLE.ROW_WID(+) AND
W_ETL_RUN_STEP.STEP_WID = W_ETL_STEP.ROW_WID
ORDER BY W_ETL_DEFN_RUN.ETL_PROC_WID DESC, W_ETL_RUN_STEP.DEPTH ASC