SELECT 
row_wid as "step_wid",
last_upd as "last_upd",
name as "step_name",
cmd_name as "cmd_name",
fl_cmd_name as "fl_cmd_name",
type_wid as "type_wid",
phase_wid as "phase_wid",
exec_wid as "exec_wid",
arguments as "arguments",
folder_wid as "folder_wid",
bld_img_flg as "bld_img_flg",
trunc_fullload_flg as "trunc_fullload_flg",
trunc_flg as "trunc_flg",
src_dbconn_wid as "src_dbconn_wid",
trgt_dbconn_wid as "trgt_dbconn_wid",
comments as "comments",
template_flg as "template_flg",
internal_flg as "internal_flg",
optional_flg as "optional_flg",
analyze_flg as "analyze_flg",
inactive_flg as "inactive_flg",
cont_on_err_flg as "cont_on_err_flg",
priority as "priority",
app_wid as "source_system_container",
version_id as "version_id",
pre_fl_command as "pre_fl_command",
pre_command as "pre_command",
post_fl_command as "post_fl_command",
post_command as "post_command",
group_flg as "group_flg",
restart_all_flg as "restart_all_flg",
grp_serial_flg as "grp_serial_flg"
FROM 
ORACLEDAC.W_ETL_STEP